@extends('layouts.admin')

@section('content')
    <div class="col-md-12">
        <div class="row justify-content-center" >
            <div class="card" >
                <div class="container">
                    <div class="card-header card-header-icon card-header-rose">
                        <div class="card-icon">
                            <i class="material-icons">perm_identity</i>
                        </div>
                        <h4 class="card-title"><span style="font-weight: 400;"><strong>Student Management System</strong></span></h4>
                    </div>
                    <div class="card-body">
                        <div errors></div>
                        <div class="row">
                            <p><span style="font-weight: 400;"><strong>Student management systems</strong>
                            software is used to help in managing staff details, students’ admission and mark sheet activities.</span></p>
                            <p><span style="font-weight: 400;">&#8220;Student Management System (SMS) is a solution tool that is designed to track,
                            maintain and manage all the data generated by a School, including the marks of a student, their status, their term wise mark
                            records, etc.,&#8221;</span></p> <p><span style="font-weight: 400;">Think of it as a big database that stores all the student
                                    records, and also manages the tasks. It simplifies the handling process of the administrative work like:</span></p>
                            <ul>
                                <li><span style="font-weight: 400;"> </span><span style="font-weight: 400;">Details of Staff:</span></li>
                                <li><span style="font-weight: 400;"> </span><span style="font-weight: 400;">Student Admissions Information:</span></li>
                                <li><span style="font-weight: 400;"> </span><span style="font-weight: 400;">Student Mark sheet:</span></li>
                            </ul>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{{--        <p><span style="font-weight: 400;">&#8220;Student Management System (SMS) is a solution tool that is designed to track,--}}
{{--                maintain and manage all the data generated by a School, including the grades of a student, their attendance, their interpersonal activities--}}
{{--                records, etc.,&#8221;</span></p> <p><span style="font-weight: 400;">Think of it as a big database that stores all the day-to-day school--}}
{{--                information, and student records, and also manages the tasks. It simplifies the handling process of the administrative work like:</span></p>--}}
{{--        <ul> <li><span style="font-weight: 400;"> </span><span style="font-weight: 400;">Student Admissions information:</span></li> </ul>--}}
{{--        <p><span style="font-weight: 400;"><strong>Student management systems</strong>--}}
{{--                software is used to help in managing all the students’ admission activities, like enrolling in a course.</span></p>--}}
{{--    </div>--}}
@endsection
@push('js')
    <script>
        app.controller('myCtrl', function ($scope, $controller, api, utils) {
            angular.extend(this, $controller('resourceController', {$scope:$scope, api:api, utils:utils}));
        });
    </script>
@endpush
@push('css')
    <style>
        .job-group{
            padding: 6px;
            margin: 2px;
            border-bottom: 1px solid #eee;
        }
        .job-group:hover{
            background-color: ghostwhite;
        }
        @media screen and (max-width: 576px) {
            .card .card-body {
                padding: 13px;
            }
            .alert {
                padding: 12px 6px;
            }
        }
    </style>
@endpush
